<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Interop.zkemkeeper">
      <HintPath>..\..\Master\Fingerprint_X100-C_SDK\NEW SDK Colour\NEW SDK Colour\SDK 64 Bit\Communication Protocol SDK(64Bit Ver6.2.3.9)\Demo\C#\TFT_x64\RTEvents\obj\Release\Interop.zkemkeeper.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
